services:
  elasticsearch:
    build: ./elasticsearch
    container_name: elastic-1
    networks:
      - network-liferay-stack
    ports: 
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - node.name=elastic-1
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
  haproxy:
    build: ./haproxy
    container_name: haproxy
    depends_on:
      - liferay
    networks:
      - network-liferay-stack
    ports:
      - 80:80
      - 9999:9999
  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.5
    container_name: kibana 
    networks:
      - network-liferay-stack
    ports:
      - 5601:5601 
    environment:
      ELASTICSEARCH_HOSTS: http://elastic-1:9200
  liferay:
    build: ./liferay
    container_name: liferay
    depends_on:
      - elasticsearch
      - mysql
    networks:
      - network-liferay-stack
# Note: In production systems, you wouldn't expose these ports publicly
    ports:
      - 8080:8080
      - 127.0.0.1:11311:11311
    environment:
      LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_DRIVER_UPPERCASEC_LASS_UPPERCASEN_AME: org.postgresql.Driver
      LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_PASSWORD: secret
      LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_URL: jdbc:postgresql://postgres:5432/lportal
      LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_USERNAME: postgres
    volumes:
      - liferay-data:/opt/liferay/data
      - liferay-work:/opt/liferay/work
  mysql:
    build: ./mysql
    container_name: mysql
    networks:
      - network-liferay-stack
## Note: In production systems, you wouldn't expose this port publicly
    ports:
      - 3306:3306
    environment:
# TODO: Create user liferay
#      MYSQL_USER: liferay
#      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_ROOT_HOST: '%' 
#      MYSQL_ROOT_HOST: *.* 
    volumes:
      - mysql:/var/lib/mysql
  postgres:
    build: ./postgres
    container_name: postgres
    networks:
      - network-liferay-stack
## Note: In production systems, you wouldn't expose this port publicly
#    ports:
#  - 5432:5432
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres:/var/lib/postgresql/data
networks:
  network-liferay-stack:
    name: network-liferay-stack
volumes:
  elasticsearch:
  liferay-data:
  liferay-work:
  mysql:
  postgres:
